# Generated by Django 4.2 on 2023-08-25 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('reference', models.TextField(default=False, verbose_name='منابع')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزسانی')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-update', '-publish'),
            },
        ),
        migrations.CreateModel(
            name='Ourproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'محصولات ما',
                'verbose_name_plural': 'محصولات ما',
            },
        ),
        migrations.CreateModel(
            name='Ourservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'خدمات ما',
                'verbose_name_plural': 'خدمات ما',
            },
        ),
        migrations.CreateModel(
            name='Oursolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'راهکار ما',
                'verbose_name_plural': 'راهکارهای ما',
            },
        ),
    ]
