# Generated by Django 4.2 on 2023-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.TextField(verbose_name='منابع'),
        ),
    ]
