# Generated by Django 4.2 on 2023-08-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='ourproducts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='oursolutions',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزسانی'),
        ),
        migrations.AlterField(
            model_name='ourproducts',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ourproducts',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ourproducts',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='oursolutions',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='oursolutions',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='oursolutions',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
