# Generated by Django 4.2 on 2023-08-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='لوگو')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='JobPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'فرصت شغلی',
                'verbose_name_plural': 'فرصت های شغلی',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('expration_code', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(verbose_name='تاریخ')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('field_of_activity', models.CharField(choices=[('Product', 'Product'), ('Services available', 'Services available')], max_length=100, verbose_name='حوضه فعالیت')),
                ('activity_province', models.CharField(max_length=100, verbose_name='استان فعالیت')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('degree_of_education', models.CharField(choices=[('Diploma', 'Diploma'), ('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100, verbose_name='میزان تحصیلات')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('skill', models.TextField(verbose_name='مهارت')),
                ('history', models.IntegerField(verbose_name='تجربه')),
                ('type_of_cooperation', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Project', 'Project')], max_length=100, verbose_name='نوع همکاری')),
                ('verification_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to='us.otp')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
