# Generated by Django 4.2.3 on 2023-08-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created', models.DateTimeField()),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('field_of_activity', models.CharField(choices=[('Product', 'Product'), ('Services available', 'Services available')], max_length=100)),
                ('activity_province', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('degree_of_education', models.CharField(choices=[('Diploma', 'Diploma'), ('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('skill', models.TextField()),
                ('history', models.IntegerField()),
                ('type_of_cooperation', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Project', 'Project')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.RenameModel(
            old_name='customers',
            new_name='Aboutus',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='logo',
            new_name='image',
        ),
    ]
