# Generated by Django 4.2.3 on 2023-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpos',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='jobpos',
            name='description_advantages',
            field=models.TextField(null=True, verbose_name='مزایا'),
        ),
        migrations.AddField(
            model_name='jobpos',
            name='description_requirements',
            field=models.TextField(null=True, verbose_name='نیازمندی ها'),
        ),
    ]
