# Generated by Django 4.2.3 on 2023-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_jobpos_description_jobpos_description_advantages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpos',
            name='description_advantages',
            field=models.JSONField(blank=True, null=True, verbose_name='مزایا'),
        ),
        migrations.AlterField(
            model_name='jobpos',
            name='description_requirements',
            field=models.JSONField(blank=True, null=True, verbose_name='نیازمندی ها'),
        ),
    ]
