# Generated by Django 4.2.1 on 2023-08-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_contactus_customer_rename_customers_aboutus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما'},
        ),
    ]
