# Generated by Django 4.2.1 on 2023-08-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'فرصت شغلی',
                'verbose_name_plural': 'فرصت های شغلی',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
    ]
