# Generated by Django 4.2.3 on 2023-08-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_career_alter_aboutus_options_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'فرصت شغلی',
                'verbose_name_plural': 'فرصت های شغلی',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('expration_code', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='activity_province',
            field=models.CharField(max_length=100, verbose_name='استان فعالیت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='degree_of_education',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100, verbose_name='میزان تحصیلات'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='field_of_activity',
            field=models.CharField(choices=[('Product', 'Product'), ('Services available', 'Services available')], max_length=100, verbose_name='حوضه فعالیت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='field_of_study',
            field=models.CharField(max_length=100, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='history',
            field=models.IntegerField(verbose_name='تجربه'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='skill',
            field=models.TextField(verbose_name='مهارت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='type_of_cooperation',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Project', 'Project')], max_length=100, verbose_name='نوع همکاری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='verification_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to='us.otp'),
        ),
    ]
