# Generated by Django 4.2.3 on 2023-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0005_alter_jobpos_description_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpos',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
