# Generated by Django 4.2 on 2023-08-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0005_jobpos_otp_delete_career_alter_aboutus_description_and_more'),
        ('us', '0005_otp_alter_aboutus_description_alter_aboutus_image_and_more'),
    ]

    operations = [
    ]
