# Generated by Django 4.2.3 on 2023-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0006_jobpos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpos',
            name='title_2',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
