# Generated by Django 4.2.3 on 2023-08-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0007_jobpos_title_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpos',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobpos',
            name='title_2',
        ),
    ]
