# Generated by Django 4.2.3 on 2023-08-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0008_rename_title_jobpos_job_title_remove_jobpos_title_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpos',
            old_name='job_title',
            new_name='title',
        ),
    ]
