# Generated by Django 4.2.3 on 2023-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0009_rename_job_title_jobpos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpos',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
