# Generated by Django 4.2.3 on 2023-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0010_jobpos_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpos',
            name='resume',
        ),
    ]
