# Generated by Django 4.2.3 on 2023-08-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0011_resume_remove_jobpos_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
