# Generated by Django 4.2.3 on 2023-08-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0012_remove_resume_resume_resume_file_resume_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
