# Generated by Django 4.2.3 on 2023-08-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0013_rename_file_resume_resume_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
