# Generated by Django 4.2.3 on 2023-08-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0014_alter_resume_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='jobpos',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='jobpos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
