# Generated by Django 4.2.3 on 2023-08-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0015_delete_resume_jobpos_resume_jobpos_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpos',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobpos',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('resume', models.FileField(null=True, upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.jobpos')),
            ],
        ),
    ]
