# Generated by Django 4.2.3 on 2023-08-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0016_remove_jobpos_resume_remove_jobpos_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
