# Generated by Django 4.2.1 on 2023-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0019_rename_field_of_activity_contactus_area_of_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='fild_of_activity',
        ),
        migrations.AddField(
            model_name='contactus',
            name='field_of_activity',
            field=models.CharField(choices=[('خدمات دهنده', 'خدمات دخنده'), ('سرویس دهنده', 'سرویس دهنده')], default=1, max_length=200, verbose_name='حوضه فعالیت'),
            preserve_default=False,
        ),
    ]
