# Generated by Django 4.2.3 on 2023-08-30 20:16

from django.db import migrations, models
import iranian_cities.models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0021_remove_contactus_city_remove_contactus_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='city',
            field=models.CharField(default=1, max_length=200, verbose_name=iranian_cities.models.Shahr),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='state',
            field=models.CharField(default=1, max_length=200, verbose_name=iranian_cities.models.Ostan),
            preserve_default=False,
        ),
    ]
