# Generated by Django 4.2.3 on 2023-08-30 20:22

from django.db import migrations
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('us', '0022_contactus_city_contactus_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='city',
            field=iranian_cities.fields.ShahrField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='state',
            field=iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan', verbose_name='استان'),
        ),
    ]
